apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: sondresjo/express-backend-typescript-example:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1025